export const InputLengthConfig = {
    NUMBER_MAX_LENGTH: 999999999,
    COMMENT: 2000,
    INFORMATION_SOURCE: 500,
    TEXT_DEFAULT_MAX_LENGTH: 50,
    TEXT_LONG_DEFAULT_MAX_LENGTH: 200,
    TEXTAREA_DEFAULT_MAX_LENGTH: 500,
    GRAPH_SEARCH_MIN_LENGTH: 3,
    LOGIN_PASSWORD_MIN_LENGTH: 5,
    LOGIN_USERNAME_MIN_LENGTH: 5
};
